# Generated by Django 3.0.1 on 2020-02-05 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='result',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_hr_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 13, 16, 8, 152998, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
