# Generated by Django 3.0.1 on 2020-02-10 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200205_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='date_time',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_date',
            field=models.DateTimeField(default=datetime.date(2020, 2, 10)),
        ),
    ]
